output_file_path = "../slate/source/index.html.md"
base_file_path = "templates/base.template.md"

[[repos]]
url = "git@github.com:SKOOTUK/endpoint-send_contacts.git"
branch = "master"
path = "README.md"
