output_file_path = "../slate/source/index.html.md"
base_file_path = "templates/base.template.md"
endpoints_base_file_path = "templates/base_endpoints.template.md"


repos = [
"ios_repo",
"android_repo",
"service_repos",
]

[[ios_repo]]
url = "git@github.com:SKOOTUK/ios.git"
branch = "master"
path = "README.md"


[[android_repo]]
url = "git@github.com:SKOOTUK/android.git"
branch = "master"
path = "README.md"


[[service_repos]]
url = "git@github.com:SKOOTUK/backend_services.git"
branch = "master"
path = "README.md"


[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-register_phone.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-licence.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-driver_location.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-cars.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-start_ride.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-choose_driver.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-trip_info.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-finish_trip.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-cancel_ride.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-shared_drive.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-shared_drives.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-transactions.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-save_customer_card.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-coupons.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-payment_pending.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-bank_account.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-withdraw.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-send_contacts.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-friends.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-image.git"
branch = "master"
path = "README.md"
[[endpoint_repos]]
url = "git@github.com:SKOOTUK/endpoint-upload.git"
branch = "master"
path = "README.md"
