version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.7.1


jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - restore_cache:
          keys:
            # Partial cache if changes
            - v1-repo-cache-{{ checksum "generate/config.toml" }}
            - v1-repo-cache-
      - add_ssh_keys:
          # WARN when adding to circleci project, do not add hostname as will only used a single
          # https://circleci.com/docs/2.0/add-ssh-key/#adding-multiple-keys-with-blank-hostnames
          fingerprints:
            - "23:e9:f3:52:3a:d3:03:2f:b5:79:1e:e0:21:3e:0d:b8"  # endpoint-send_contacts
            - "75:e7:94:1b:80:9e:8d:23:96:13:cc:d5:ba:0e:b0:08"  # endpoint-save_customer_card
            - "43:90:55:ce:53:e2:61:73:22:74:fa:5a:79:30:08:b1"  # endpoint-shared_drives
            - "0c:c7:19:ac:78:30:6a:9d:40:f7:79:98:f0:b4:84:8b"  # endpoint-shared_drive
      - run:
          name: Setup VirtualEnv for doc generation
          command: |
            virtualenv .venv_gen
            . .venv_gen/bin/activate
            pip install --no-cache-dir -r generate/requirements.txt
      - run:
          name: Generate documentation
          command: |
            . .venv_gen/bin/activate
            cd generate
            python generate.py
      - persist_to_workspace:
          root: slate/source
          paths:
            - index.html.md
      - save_cache:
          # regenerates cache if config changes
          key: v1-repo-cache-{{ checksum "generate/config.toml" }}
          paths:
            - generate/repos

  docker-build-and-push:
    machine:
      image: circleci/classic:201808-01
      docker_layer_caching: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Replace Slate index.html.md
          command: |
            rm slate/source/index.html.md
            cp /tmp/workspace/index.html.md slate/source/index.html.md
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          path: slate
          image: docs
          registry-url: eu.gcr.io
      - run:
          name: Docker tag and push
          command: |
            docker tag eu.gcr.io/$GOOGLE_PROJECT_ID/docs eu.gcr.io/$GOOGLE_PROJECT_ID/docs:prod-$CIRCLE_BUILD_NUM
            docker push eu.gcr.io/$GOOGLE_PROJECT_ID/docs:prod-$CIRCLE_BUILD_NUM

workflows:
  build:
    jobs:
      - build
      - docker-build-and-push:
          requires:
            - build
          filters:
            branches:
              only:
                - master
