version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.7.1

jobs:
  generate-documentation:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv for doc generation
          command: |
            virtualenv .venv_gen
            . .venv_gen/bin/activate
            pip install --no-cache-dir -r generate/requirements.txt
      - run:
          name: Generate documentation
          command: |
            . .venv_gen/bin/activate
            cd generate
            python generate.py
      - persist_to_workspace:
          root: slate/source
          paths:
            - index.html.md

  build-and-push:
    executor: gcp-gcr/default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          command: |
            echo $ls
      - run:
          name: Replace Slate index.html.md
          command: |
            rm slate/source/index.html.md
            cp /tmp/workspace/index.html.md slate/source/index.html.md
            cat slate/source/index.html.md
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          path: slate
          image: generated_docs_slate
      - gcp-gcr/push-image:
          image: generated_docs_slate

workflows:
  commit:
    jobs:
      - generate-documentation
      - build-and-push:
          requires:
            - generate-documentation
