version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=api_doc_generator' >> $BASH_ENV 
            virtualenv generator
            . generator/bin/activate
            pip install --no-cache-dir -r generate/requirements.txt
      - run:
          name: Generate documentation
          command: |
            . generator/bin/activate
            cd generate
            python generate.py
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            cd slate
            docker build -t $IMAGE_NAME:$TAG .

workflows:
  main:
    jobs:
      - build
