version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.7.1

jobs:
  generate-documentation:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - restore_cache:
          keys:
            # Partial cache if changes
            - v1-repo-cache-{{ checksum "generate/config.toml" }}
            - v1-repo-cache-
      - add_ssh_keys:
          fingerprints:
            # - "f3:3f:9d:1d:0b:07:fb:ab:ad:dc:5f:e7:e1:4c:86:b7"  # endpoint-register_phone
            - "23:e9:f3:52:3a:d3:03:2f:b5:79:1e:e0:21:3e:0d:b8"  # endpoint-send_contacts
      - run:
          name: Setup VirtualEnv for doc generation
          command: |
            virtualenv .venv_gen
            . .venv_gen/bin/activate
            pip install --no-cache-dir -r generate/requirements.txt
      - run:
          name: Generate documentation
          command: |
            . .venv_gen/bin/activate
            cd generate
            python generate.py
      - persist_to_workspace:
          root: slate/source
          paths:
            - index.html.md
      - save_cache:
          # regenerates cache if config changes
          key: v1-repo-cache-{{ checksum "generate/config.toml" }}
          paths:
            - generate/repos

  build-and-push:
    executor: gcp-gcr/default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          command: |
            echo $ls
      - run:
          name: Replace Slate index.html.md
          command: |
            rm slate/source/index.html.md
            cp /tmp/workspace/index.html.md slate/source/index.html.md
            cat slate/source/index.html.md
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          path: slate
          image: generated_docs_slate
      - gcp-gcr/push-image:
          image: generated_docs_slate

workflows:
  commit:
    jobs:
      - generate-documentation
      - build-and-push:
          requires:
            - generate-documentation
